---
title: "Exercise#1"
author: "Aldair Lein"
date: "2025-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('scripts/abs_path.r', chdir = TRUE)
source('scripts/install_libraries.r', chdir = TRUE)

```

## R Markdown

```{r read data}
wine <- read.csv(path_data('winequality-white.csv'), sep=";")
wine[] <- lapply(wine, as.numeric)
wine$quality_binary <- ifelse(wine$quality > 5, 1, 0)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
good_wines <- wine[wine$quality_binary == 1, ]
bad_wines <- wine[wine$quality_binary == 0, ]
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r pressure, echo=FALSE}
library(ggplot2)
ggplot(good_wines, aes(x = residual.sugar)) + geom_histogram(binwidth = 1, fill = "skyblue", color = "black")
ggplot(bad_wines, aes(x = residual.sugar)) + geom_histogram(binwidth = 1, fill = "lightcoral", color = "black")
```
